name: Deploy site

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy site to AWS S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      WORKSPACE: original
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        target: wasm32-unknown-unknown

    - name: Setup Cargo cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: rust-cargo
        workspaces: ${{ env.WORKSPACE }}

    - name: Build
      working-directory: ${{ env.WORKSPACE }}
      run: |
        cargo install --locked trunk
        cargo install wasm-pack
        wasm-pack build --target web --out-name wasm --out-dir ./static

    - name: Copy site to s3 with the AWS CLI
      run: |
        aws --region ${{ secrets.AWS_REGION }} s3 sync --acl private $WORKSPACE/static/ s3://${{ secrets.S3_BUCKET }}/${{ secrets.S3_PREFIX }}/

    - name: Request CloudFront invalidation of all objects
      run: |
        aws --region ${{ secrets.AWS_REGION }} cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
